-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 23:08:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
create database salessystems;
use salessystems;
CREATE TABLE `buyers` (
  `id` INT NOT NULL auto_increment,
  `username` VARCHAR(30) NOT NULL,
  `gmail` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
insert into buyers(username, gmail, password) values
('Carlos Ulloa', 'ulloa@gmail.com', 12345),
('Marcos Chacon', 'chacon@gmail.com', 12345),
('Joyce Toledo', 'toledo@gmail.com', 12345),
('Yerni Potosme', 'potosme@gmail.com', 12345),
('Ezequiel Castillo', 'castillo@gmail.com', 12345),
('Joseph Tatnai', 'tatnai@gmail.com', 12345),
('John Romero', 'romero@gmail.com', 12345),
('Oscar Muñoz', 'muñoz@gmail.com', 12345),
('Melvin Rivas', 'rivas@gmail.com', 12345),
('Genesis Sandoval', 'sandoval@gmail.com', 12345),
('Henry Natanael', 'natanael@gmail.com', 12345),
('Ricardo Gomez', 'gomez@gmail.com', 12345),
('Arnaldo Colombia', 'colombia@gmail.com', 12345),
('Luis Vargas', 'vargas@gmail.com', 12345),
('Jostin Acuña', 'acuña@gmail.com', 12345),
('Francis Garcia', 'garcia@gmail.com', 12345);
select * from buyers;
-- Crear una consulta donde nos permita ver las columnas de id, clientes, productos y la marca
select b.id, b.username, p.nameproduct, r.namebrand from buyers b inner join product p on b.id = p.created_by
inner join brand r on b.id = r.id;

-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE `brand`(
  `id` INT NOT NULL auto_increment,
  `namebrand` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
insert into brand(namebrand) values
('Apple'),('Xbox'),('Microsft'),('Samsung'),('Apple'),('Samsung'),('SmartTV'),('Xbox'),('Microsft'),
('Asus'), ('Nike'),('Apple'),('Joma'),('Adidas'),('Dell'),('Hp');
select * from brand;
-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE `product`(
  `id` INT NOT NULL auto_increment,
  `nameproduct` VARCHAR(30) NOT NULL,
  `bran_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `brand_id_idx` (`bran_id` ASC) VISIBLE,
  CONSTRAINT `created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `salessystems`.`buyers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`bran_id`)
    REFERENCES `salessystems`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
insert into product(nameproduct, bran_id, created_by) values
('12proMax', 1, 1), 
('Xbox360', 2, 2), 
('License365', 3, 3), 
('S22 Ultra', 4, 4), 
('Ipad Mini', 1, 5),
('S9+', 4, 6), 
('SmartTV60', 7, 7), 
('Xbox One', 2, 8), 
('LicenseC#', 3, 9), 
('Rog5', 10, 10),
('AirForceOne', 11, 11), 
('Mac', 1, 12), 
('suitsJ', 13, 13), 
('shoesAdd', 14, 14), 
('MonitorGamer22+', 15, 15),
('TecladoGamer', 16, 16);
select * from product;
-- -----------------------------------------------------
-- Table `mydb`.`step`
-- -----------------------------------------------------
CREATE TABLE `step`(
  `id` INT NOT NULL auto_increment,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `salessystems`.`buyers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
select * from step;

-- -----------------------------------------------------
-- Table `mydb`.`step_detail`
-- -----------------------------------------------------
CREATE TABLE`step_detail`(
  `id` INT NOT NULL auto_increment,
  `step_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_step_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_step_has_product_step1_idx` (`step_id` ASC) VISIBLE,
  CONSTRAINT `fk_step_has_product_step1`
    FOREIGN KEY (`step_id`)
    REFERENCES `salessystems`.`step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_step_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `salessystems`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
select * from step_detail;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
